### PR TITLE
Fix various missing #include and required namespace qualifiers

### PR DESCRIPTION
**Pull request by yangskyboxlabs**
This patchset fixes a number of trivial compilation issues that were found when attempting to add Linux support to `libHttpClient`. 

I have not tested these on all platforms, or attempted to understand why the current incorrect forms work, but they are harmless changes AFAICT.

### CODE REVIEW

**Review by jasonsandlin — APPROVED** [review]

**Comment by jasonsandlin** [comment]
Thanks.  Can you fill out the CLA for the bot so we can get this merged in?

**Review by jplafonta — APPROVED** [review]
:shipit:

**Comment by yangskyboxlabs** [comment]
I apologize on the delay on that. This work is happening for Mojang under a partner studio, and we've been trying to get some clarity on if was OK for me to simply accept the CLA. So far Trust & Compliance doesn't seem to have an answer.

If someone happen to be aware of some MS-wide policy re: OSS contributions by contractors, that would be very helpful.

**Comment by jasonsandlin** [comment]
I'm not aware of that policy.  I recommend that you and your Microsoft rep email the folks here: https://github.com/microsoft/opensource.microsoft.com#code-of-conduct

**Comment by jasonsandlin** [comment]
These are all minor fixes, so I'll get these in

**Pull request closed without merging**
